apiVersion: v1
kind: Secret
metadata:
  name: repo-example-os
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  name: example/os
  type: git
  url: https://gitlab.sikademo.com/example/os.git
  username: ondrejsika
  password: asdfasdf
