apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: foo
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-11-28_counter_helm_chart.git
    path: .
    helm:
      releaseName: counter
      valuesObject:
        host: counter.k8s.sikademo.com
